version: "3.8"

services:
  backend:
    build:
      context: ./project/backend
    command: /start_prod.sh
    networks:
      - django-nginx
    volumes:
      - ./project/backend:/code
      - django-static:/code/static
      - django-media:/code/media
    depends_on:
      - db

  db:
    image: postgres:15.3-alpine
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    networks:
      - django-nginx

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: always

    ports:
      - 8000:80
    networks:
      - django-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./project/backend/logs:/srv/app/logs
      
      - django-static:/usr/src/app/static
      - django-media:/usr/src/app/media
    depends_on:
      - backend

volumes:
  django-static:
  django-media:

networks:
  django-nginx:
    driver: bridge
